[package]
name = "do-alerts-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
dotenv = "0.15.0"
imap = "3.0.0-alpha.10"
regex = "1.7.1"
regex-macro = "0.2.0"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
serde_json = "1.0.93"
